#!/usr/bin/env bash
set -euo pipefail

required_files=(
  "README.md"
  "RELEASE_NOTES.md"
  ".github/pull_request_template.md"
  ".github/ISSUE_TEMPLATE/config.yml"
  ".github/ISSUE_TEMPLATE/documentation-improvement.md"
  ".github/ISSUE_TEMPLATE/security-sanitization-review.md"
  "assets/README.md"
  "assets/screenshots/README.md"
  "assets/diagrams/README.md"
  "assets/diagrams/starter-kit-overview.png"
  "assets/diagrams/starter-kit-overview.svg"
  "assets/diagrams/golden-path-workflow.svg"
  "assets/diagrams/lab-topology-placeholder.svg"
  "assets/diagrams/remote-access-flow-placeholder.svg"
  "assets/diagrams/ansible-control-flow-placeholder.svg"
  "blog/README.md"
  "blog/build-secure-linux-network-engineering-lab.md"
  "blog/devto-practical-home-lab-starter-kit-launch.md"
  "CHANGELOG.md"
  "LICENSE.md"
  "CONTRIBUTING.md"
  "SECURITY.md"
  "docs/architecture.md"
  "docs/hardware-bom.md"
  "docs/lab-deployment-checklist.md"
  "docs/golden-path-operational-workflow.md"
  "docs/linux-host-setup.md"
  "docs/gns3-setup.md"
  "docs/remote-access.md"
  "docs/security-hardening.md"
  "docs/ansible-workflows.md"
  "docs/troubleshooting.md"
  "docs/product-roadmap.md"
  "docs/example-lab-topology.md"
  "docs/release-checklist.md"
  "docs/diagram-guide.md"
  "docs/publication-checklist.md"
  "docs/sanitized-example-policy.md"
  "docs/repo-boundary-policy.md"
  "docs/local-release-process.md"
  "docs/github-publication-process.md"
  "docs/public-demo-walkthrough.md"
  "docs/screenshot-plan.md"
  "docs/obs-recording-setup.md"
  "docs/video-production-checklist.md"
  "docs/terminal-presentation-guidelines.md"
  "diagrams/README.md"
  "diagrams/rendering-notes.md"
  "diagrams/golden-path-workflow.mmd"
  "diagrams/lab-topology.mmd"
  "diagrams/remote-access-flow.mmd"
  "diagrams/ansible-control-flow.mmd"
  "templates/ufw-rules.example.sh"
  "templates/ssh-hardening-checklist.md"
  "templates/lab-inventory.example.ini"
  "templates/network-device-vars.example.yml"
  "ansible/inventory.example.ini"
  "ansible/README.md"
  "ansible/playbooks/ping-lab.yml"
  "ansible/playbooks/show-version.yml"
  "ansible/playbooks/backup-running-config.example.yml"
  "ansible/playbooks/show-interfaces.example.yml"
  "ansible/playbooks/show-inventory.example.yml"
  "ansible/group_vars/all.example.yml"
  "ansible/group_vars/cisco_ios.example.yml"
  "ansible/group_vars/arista_eos.example.yml"
  "video/README.md"
  "video/walkthrough-outline.md"
  "video/ai-voiceover-script-draft.md"
  "video/final-walkthrough-v0.1-script.md"
  "video/final-walkthrough-v0.1-narration-only.md"
  "media/README.md"
  "media/thumbnail-concepts.md"
  "media/video-folder-workflow.md"
  "media/raw/.gitkeep"
  "media/edited/.gitkeep"
  "media/audio/.gitkeep"
  "media/thumbnails/.gitkeep"
  "media/screenshots/.gitkeep"
  "product/paid-bundle-outline.md"
  "product/launch-checklist.md"
  "product/content-funnel.md"
  "product/free-vs-paid-scope.md"
  "product/v0.1-launch-plan.md"
  "product/pdf-bundle-table-of-contents.md"
  "product/github-launch-readme-review.md"
  "product/v0.1-release-summary.md"
  "product/next-phase-roadmap.md"
  "product/github-repo-description.md"
  "product/v0.1-github-release-draft.md"
  "product/social-launch-draft.md"
  "product/linkedin-launch-post.md"
  "product/reddit-launch-guidance.md"
  "product/content-expansion-ideas.md"
  "product/video-expansion-roadmap.md"
  "product/linkedin-launch-post-v2.md"
  "product/reddit-value-first-post.md"
  "product/paid-bundle-v0.1-outline.md"
  "product/gumroad-listing-draft.md"
  "product/launch-sequence-tonight.md"
  "product/golden-path-content-plan.md"
  "scripts/package-release.sh"
  "scripts/bootstrap-lab-host.example.sh"
  "scripts/setup-ufw-baseline.example.sh"
  "scripts/validate-lab-host.example.sh"
  "scripts/run-golden-path-demo.example.sh"
)

fail=0

for file in "${required_files[@]}"; do
  if [[ ! -f "$file" ]]; then
    echo "Missing required file: $file"
    fail=1
    continue
  fi

  if [[ "$file" != *.png && "$(basename "$file")" != ".gitkeep" ]]; then
    line_count="$(wc -l < "$file" | tr -d ' ')"
    if [[ "$line_count" -lt 3 ]]; then
      echo "Required file has too little content: $file"
      fail=1
    fi
  fi
done

required_terms=(
  "README.md:secure"
  "README.md:GNS3"
  "README.md:Ansible"
  "README.md:What This Is Not"
  "README.md:Technical Diagrams"
  "README.md:Golden Path Workflow"
  "README.md:With this repo today"
  "README.md:v0.1 public foundation"
  "README.md:Key Features"
  "README.md:Why This Project Exists"
  "README.md:Future Roadmap"
  "README.md:What You'll Build"
  "README.md:assets/diagrams/starter-kit-overview.png"
  "README.md:assets/diagrams/lab-topology-placeholder.svg"
  "README.md:assets/diagrams/remote-access-flow-placeholder.svg"
  "README.md:assets/diagrams/ansible-control-flow-placeholder.svg"
  "README.md:docs/hardware-bom.md"
  "README.md:docs/lab-deployment-checklist.md"
  "README.md:docs/golden-path-operational-workflow.md"
  "README.md:assets/diagrams/golden-path-workflow.svg"
  "README.md:ansible/playbooks/show-interfaces.example.yml"
  "README.md:blog/"
  "README.md:blog/build-secure-linux-network-engineering-lab.md"
  "RELEASE_NOTES.md:v0.1.0"
  ".github/pull_request_template.md:Safety Review"
  ".github/ISSUE_TEMPLATE/config.yml:blank_issues_enabled"
  ".github/ISSUE_TEMPLATE/documentation-improvement.md:Documentation improvement"
  ".github/ISSUE_TEMPLATE/security-sanitization-review.md:Security or sanitization review"
  "assets/README.md:Assets"
  "assets/screenshots/README.md:Screenshot Assets"
  "assets/diagrams/README.md:Diagram Assets"
  "assets/diagrams/README.md:primary README hero visual"
  "assets/diagrams/starter-kit-overview.svg:<svg"
  "assets/diagrams/golden-path-workflow.svg:<svg"
  "assets/diagrams/golden-path-workflow.svg:Golden Path operational workflow"
  "assets/diagrams/lab-topology-placeholder.svg:Sanitized lab topology example"
  "assets/diagrams/lab-topology-placeholder.svg:<svg"
  "assets/diagrams/remote-access-flow-placeholder.svg:Sanitized remote access flow example"
  "assets/diagrams/remote-access-flow-placeholder.svg:<svg"
  "assets/diagrams/ansible-control-flow-placeholder.svg:Sanitized Ansible control flow example"
  "assets/diagrams/ansible-control-flow-placeholder.svg:<svg"
  "blog/README.md:Blog Drafts"
  "blog/README.md:devto-practical-home-lab-starter-kit-launch.md"
  "blog/README.md:future Golden Path article"
  "blog/build-secure-linux-network-engineering-lab.md:GNS3"
  "blog/build-secure-linux-network-engineering-lab.md:Ansible"
  "blog/build-secure-linux-network-engineering-lab.md:Linux"
  "blog/build-secure-linux-network-engineering-lab.md:remote access"
  "blog/devto-practical-home-lab-starter-kit-launch.md:https://brentf.io/lab"
  "blog/devto-practical-home-lab-starter-kit-launch.md:Linux"
  "blog/devto-practical-home-lab-starter-kit-launch.md:GNS3"
  "blog/devto-practical-home-lab-starter-kit-launch.md:Ansible"
  "blog/devto-practical-home-lab-starter-kit-launch.md:remote access"
  "CHANGELOG.md:v0.1.0"
  "CHANGELOG.md:dist/"
  "CONTRIBUTING.md:sanitized examples"
  "CONTRIBUTING.md:Branch Naming"
  "CONTRIBUTING.md:No-Secrets Policy"
  "SECURITY.md:Sensitive Information Rules"
  "SECURITY.md:What Counts as a Security Concern"
  "LICENSE.md:No final open source license"
  "docs/security-hardening.md:SSH"
  "docs/hardware-bom.md:Hardware and BOM Guidance"
  "docs/lab-deployment-checklist.md:Lab Deployment Checklist"
  "docs/golden-path-operational-workflow.md:Golden Path Operational Workflow"
  "docs/golden-path-operational-workflow.md:read-only validation playbooks"
  "docs/remote-access.md:UFW"
  "docs/ansible-workflows.md:inventory"
  "docs/example-lab-topology.md:Management network"
  "docs/example-lab-topology.md:diagrams/lab-topology.mmd"
  "docs/diagram-guide.md:Diagram Map"
  "docs/release-checklist.md:redaction-check.sh"
  "docs/publication-checklist.md:Publication Checklist"
  "docs/sanitized-example-policy.md:Sanitized Example Policy"
  "docs/repo-boundary-policy.md:Repository Boundary Policy"
  "docs/local-release-process.md:Local Release Process"
  "docs/github-publication-process.md:GitHub Publication Process"
  "docs/public-demo-walkthrough.md:Public Demo Walkthrough"
  "docs/screenshot-plan.md:Screenshot Plan"
  "docs/obs-recording-setup.md:OBS Recording Setup"
  "docs/obs-recording-setup.md:AI Voiceover Workflow"
  "docs/video-production-checklist.md:Video Production Checklist"
  "docs/video-production-checklist.md:Sanitization Checks"
  "docs/terminal-presentation-guidelines.md:Terminal Presentation Guidelines"
  "docs/terminal-presentation-guidelines.md:Prompt Cleanliness"
  "diagrams/README.md:Diagram Strategy"
  "diagrams/rendering-notes.md:Diagram Rendering Notes"
  "diagrams/golden-path-workflow.mmd:flowchart"
  "diagrams/lab-topology.mmd:flowchart"
  "diagrams/remote-access-flow.mmd:flowchart"
  "diagrams/ansible-control-flow.mmd:flowchart"
  "product/free-vs-paid-scope.md:Stays Free"
  "product/free-vs-paid-scope.md:Free lab deployment checklist"
  "product/v0.1-launch-plan.md:v0.1"
  "product/pdf-bundle-table-of-contents.md:Paid PDF Bundle"
  "product/github-launch-readme-review.md:GitHub Launch README Review"
  "product/v0.1-release-summary.md:v0.1 Release Summary"
  "product/next-phase-roadmap.md:Next Phase Roadmap"
  "product/github-repo-description.md:Short Description"
  "product/v0.1-github-release-draft.md:Release Title"
  "product/social-launch-draft.md:Social Launch Draft"
  "product/linkedin-launch-post.md:LinkedIn Launch Post"
  "product/reddit-launch-guidance.md:Reddit Launch Guidance"
  "product/content-expansion-ideas.md:Content Expansion Ideas"
  "product/video-expansion-roadmap.md:Video Expansion Roadmap"
  "product/linkedin-launch-post-v2.md:LinkedIn Launch Post v2"
  "product/reddit-value-first-post.md:Reddit Value-First Post"
  "product/paid-bundle-v0.1-outline.md:Paid Bundle v0.1 Outline"
  "product/gumroad-listing-draft.md:Gumroad Listing Draft"
  "product/launch-sequence-tonight.md:Launch Sequence Tonight"
  "product/golden-path-content-plan.md:Golden Path Content Plan"
  "scripts/package-release.sh:tar"
  "scripts/bootstrap-lab-host.example.sh:DRY RUN"
  "scripts/setup-ufw-baseline.example.sh:APPLY=1"
  "scripts/validate-lab-host.example.sh:Safe read-only checks"
  "scripts/run-golden-path-demo.example.sh:tree -L 2"
  "scripts/run-golden-path-demo.example.sh:ansible/inventory.example.ini"
  "scripts/run-golden-path-demo.example.sh:git diff --check"
  "video/README.md:Video Planning"
  "video/walkthrough-outline.md:Scene 1"
  "video/walkthrough-outline.md:Golden Path"
  "video/walkthrough-outline.md:Quick Demo Version"
  "video/walkthrough-outline.md:Suggested Recording Order"
  "video/walkthrough-outline.md:Narration Visual Map"
  "video/ai-voiceover-script-draft.md:Target length: 5 to 7 minutes"
  "video/ai-voiceover-script-draft.md:Short Launch Video Version"
  "video/ai-voiceover-script-draft.md:Most home labs do not"
  "video/final-walkthrough-v0.1-script.md:Final Walkthrough v0.1 Narration Script"
  "video/final-walkthrough-v0.1-script.md:0:00 Intro"
  "video/final-walkthrough-v0.1-script.md:show README"
  "video/final-walkthrough-v0.1-script.md:open Ansible workflows"
  "video/final-walkthrough-v0.1-narration-only.md:AI voice narration input"
  "video/final-walkthrough-v0.1-narration-only.md:This is the Practical Home Lab Starter Kit"
  "video/final-walkthrough-v0.1-narration-only.md:Feedback is welcome"
  "media/README.md:Media Workspace"
  "media/README.md:raw/"
  "media/thumbnail-concepts.md:Thumbnail Concepts"
  "media/thumbnail-concepts.md:YouTube Thumbnail Concepts"
  "media/video-folder-workflow.md:Video Folder Workflow"
  "media/video-folder-workflow.md:Raw Recordings"
  "templates/ufw-rules.example.sh:ufw"
  "ansible/playbooks/ping-lab.yml:ansible.builtin.wait_for"
  "ansible/playbooks/show-version.yml:show version"
  "ansible/README.md:Vendor Grouping"
  "ansible/group_vars/cisco_ios.example.yml:cisco.ios.ios"
  "ansible/group_vars/arista_eos.example.yml:arista.eos.eos"
)

for check in "${required_terms[@]}"; do
  file="${check%%:*}"
  term="${check#*:}"
  if [[ -f "$file" ]] && ! grep -Fq "$term" "$file"; then
    echo "Required term not found in $file: $term"
    fail=1
  fi
done

narration_only_file="video/final-walkthrough-v0.1-narration-only.md"
if [[ -f "$narration_only_file" ]] && grep -Eq '^\[' "$narration_only_file"; then
  echo "Narration-only script contains bracketed editor cue lines: $narration_only_file"
  fail=1
fi

ansible_example_playbooks=(
  "ansible/playbooks/backup-running-config.example.yml"
  "ansible/playbooks/show-interfaces.example.yml"
  "ansible/playbooks/show-inventory.example.yml"
)

for playbook in "${ansible_example_playbooks[@]}"; do
  if [[ -f "$playbook" ]]; then
    if ! grep -Fq "hosts:" "$playbook"; then
      echo "Ansible example playbook missing hosts: $playbook"
      fail=1
    fi
    if ! grep -Fq "tasks:" "$playbook"; then
      echo "Ansible example playbook missing tasks: $playbook"
      fail=1
    fi
  fi
done

while IFS= read -r script; do
  if ! bash -n "$script"; then
    echo "Shell script syntax check failed: $script"
    fail=1
  fi
done < <(find scripts -type f -name "*.sh" | sort)

if [[ "$fail" -ne 0 ]]; then
  echo "Validation failed."
  exit 1
fi

echo "Validation passed."
